int posX = 70;
int posY = 368;
int ancho = 500;
int alto = 50;
color colorBoton = color(0);
color colorBorde = color(0);
PFont mi_fuente;
PImage portada; 
PImage img2;    
PImage img3;    
PImage img4;    
PImage img5;   
PImage img6;
boolean mostrarportada = false;
float x1 = 0;
float x2 = 0;
float x3 = 0;
float x4 = 0;
float x5 = 0;
float velocidad = 5;

int tiempoInicioEfecto = 0; 
boolean yaGuardeElTiempo = false;
int tiempoImg2 = 0;
boolean yaGuardeImg2 = false;
int tiempoImg3 = 0;
boolean yaGuardeImg3 = false;
int tiempoImg4 = 0;
boolean yaGuardeImg4 = false;
int tiempoImg5 = 0;
boolean yaGuardeImg5 = false;

boolean ultimaImagen = false;
